@echo off
echo Stopping and removing everything (containers + volumes)...
docker-compose down -v

echo Removing old backend image...
docker rmi studiomar-backend 2>nul

echo Building Docker images from scratch (no cache)...
docker-compose build --no-cache backend

echo Starting fresh Docker services (DB and Backend)...
docker-compose up -d db backend

echo Waiting for backend to start and seed data...
timeout /t 8 /nobreak >nul

echo All services started fresh! Starting Frontend...
cd frontend
npm run dev